### ISSUE TITLE
`pow()` function in `project.py` can be optimized

### ISSUE THREAD

**Issue by shivrm** [MarkNatavio/CSC-480-Project#4]
In `project.py`, the `pow()` function has been used like this:

```py
 2 | c1 = pow(g, key) % p
 6 | g2 = pow(g, pk) % p
 7 | c2 = m * (pow(g2, key) % p)
```

The official [documentation](https://docs.python.org/3/library/functions.html#pow) for the `pow()` function states that it can accept 3 arguments: a `base`, an `exponent`, and an optional `mod` argument.

The `mod` argument is used where a large power is calculated modulo `mod`.
The documentation states that `pow(base, exponent, mod)` is *much* more efficient than `pow(base, exponent) % mod`

Therefore, these above lines can be rewritten as follows:
```py
 2 | c1 = pow(g, key, mod=p)
 6 | g2 = pow(g, pk, mod=p)
 7 | c2 = m * pow(g2, key, mod=p)
```

# Test: 
```console
$ python -m timeit -n 10000 "pow(137438953471, 2047) % 8388607"
10000 loops, best of 5: 613 usec per loop

$ python -m timeit -n 10000 "pow(137438953471, 2047, mod=8388607)"
10000 loops, best of 5: 1.26 usec per loop

**Comment by JustinParkCS** [comment]
We have made the modifications. Thank you for this helpful advice!
